### ISSUE TITLE
404 on paz-orchestrator/services/:name/config/last

### ISSUE THREAD

**Issue by jem-computer** [yldio/paz-web#11]
Has the endpoint changed?

Getting this when trying to update the configuration of a service in `paz-web/services/:name`

**Comment by lukebond** [comment]
This is working for me currently:

```
$ curl paz-orchestrator.lukeb0nd.com/services/Redis/config/last
{"doc":{"publicFacing":false,"numInstances":1,"ports":[{"container":6379,"host":6379}],"env":{"IS":"NICE"}}}
```

Can you give some more info on what you're doing when the error occurs?

**Comment by jem-computer** [comment]
I was just viewing my service ‘SimpleProxy’ that I created through the Paz web UI.

```
curl paz-orchestrator.lukeb0nd.com/services/SimpleProxy/config/last
"Key not found in database [latest!SimpleProxy]"%
```

This fails (but you’re totally right - the Redis example works) - I wonder if SimpleProxy didn’t get created properly?

**Comment by lukebond** [comment]
This endpoint proxies through to the scheduler, and it is the scheduler who is ultimately giving a 404 for a GET on the latest config. What this means is that this service has never been deployed. This isn't clear, granted :)

If you want the config most recently edited in the UI, then you want the "next" config, ie. the config that will get used when the scheduler next deploys that service. `/services/:name/config/next` is the route for that.

Note the differences: https://github.com/paz-sh/paz-orchestrator/blob/master/resources/service/controller.js#L99-L131

**Comment by lukebond** [comment]
@jongold shall we close this and put it down to a service that didn't get created correctly?

**Comment by lukebond** [comment]
Re-open if this is still an issue.
