### ISSUE TITLE
Errors on browser console when updating a unit's config

### ISSUE THREAD

**Issue by foliveira** [yldio/paz-web#14]
It seems that trying to save a new config for a unit, if we click on the Save button there's an error in the browser console and the new config isn't saved.

![Saving](https://cldup.com/Gi7GM9l_G3.png)

**Comment by jem-computer** [comment]
Looking into it now
http://discuss.emberjs.com/t/ember-data-1-0-0-beta-15-breaking-save-functionality/7343/3

**Comment by jem-computer** [comment]
https://github.com/emberjs/data/issues/2801

I think the bug will be in our service serializer.
