### ISSUE TITLE
Cannot read property 'async' of undefined - in web UI

### ISSUE THREAD

**Issue by lukebond** [yldio/paz-web#3]
![paz-web-screenshot](https://cloud.githubusercontent.com/assets/3177600/6542980/cccd1dd2-c501-11e4-80ca-09083e104eef.png)

^^ I'm seeing this and I'm a bit baffled as to what the stacktrace means. Any EmberJS folk that can help?

**Comment by lukebond** [comment]
Note that it occurs on the home/dashboard page, but before taking the screenshot I'd changed tabs.

**Comment by lukebond** [comment]
![screen shot 2015-03-07 at 19 42 23](https://cloud.githubusercontent.com/assets/3177600/6542989/1aff06dc-c502-11e4-83e4-68a600224bd5.png)

^^ Note in the above screenshot that the Network tab in Chrome devtools shows that the request to the server is working and returning the correct results.

My guess is it's something out of date in the web UI, or something that I broke when I tried to make a change lastweek :/

**Comment by jem-computer** [comment]
I'll look at it tomorrow AM if you can wait - not at my Mac right now. Assume an Ember Data API has changed; should be a small fix. 

 ^^ Note in the above screenshot that the Network tab in Chrome devtools shows that the request to the server is working and returning the correct results.
 My guess is it's something out of date in the web UI, or something that I broke when I tried to make a change lastweek :/

**Comment by lukebond** [comment]
absolutely! let me know if you find the cause as it'd be good for me to learn more about Ember.js

**Comment by lukebond** [comment]
Closing as duplicate of #4
