### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by jem-computer** [yldio/paz-web#4]
Bunch of out of date things in there; was working on it last night and ran out of steam. https://github.com/paz-sh/paz-web/tree/update-dependencies is my working branch - will finish it up today.

**Comment by lukebond** [comment]
awesome, thanks @jongold!

**Comment by jem-computer** [comment]
All working on the branch except Sass compilation - there was a recent bug in `node-sass` and I can't figure out how to fix it.

Related ticket: https://github.com/aexmachina/ember-cli-sass/issues/1 - hoping for a reply soon - barring that I'll just nuke node from my system and try again.

**Comment by lukebond** [comment]
I tried manually editing brocolli's node-sass version in package.json (to 2.0.0-beta as per sass/node-sass#467) but it still segfaults.

how is anyone using Ember at all with this issue still outstanding?

**Comment by jem-computer** [comment]
wait I got it working - will push my branch when I get to the office.

It was something with node-sass; might still switch it out to Stylus because I was really unimpressed with their response to issues though.

**Comment by lukebond** [comment]
Fixed by #5
